# nixpacks.toml

# Указываем Nixpacks использовать стандартную среду Node.js.
providers = ["node"]

# Фаза установки зависимостей
[phases.install]
# Используем 'npm ci' для быстрой и надежной установки.
cmds = ["npm ci"]

# Фаза сборки проекта
[phases.build]
# 1. Используем `db push` для синхронизации схемы Prisma с базой данных.
#    Это создаст все необходимые таблицы.
# 2. Запускаем сборку Next.js.
#    Шаг 'db seed' убран для повышения стабильности деплоя.
cmds = ["npx prisma db push", "npm run build"]

# Фаза запуска приложения
[start]
# Запускаем приложение.
cmd = "npm run start"
